[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
axum.workspace = true
chrono.workspace = true
tracing.workspace = true
anyhow = "1"
tower-http = { version = "0.5", features = ["trace"] }
occp_ws = { path = "../occp_ws" }
common = { path = "../common" }
db = { path = "../db" }
